"""migración inicial

Revision ID: 1b386c070110
Revises: 
Create Date: 2025-05-13 09:41:50.875051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b386c070110'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jugadores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=False),
    sa.Column('posicion', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('jugadores_pkey')),
    sa.UniqueConstraint('numero', name=op.f('jugadores_numero_key'))
    )
    op.create_table('partidos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('rival', sa.String(length=100), nullable=False),
    sa.Column('resultado_local', sa.Integer(), nullable=False),
    sa.Column('resultado_visitante', sa.Integer(), nullable=False),
    sa.Column('lugar', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('partidos_pkey'))
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jugador_id', sa.Uuid(), nullable=False),
    sa.Column('partido_id', sa.Uuid(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('justificacion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], name=op.f('asistencias_jugador_id_jugadores_fkey')),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], name=op.f('asistencias_partido_id_partidos_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asistencias_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asistencias')
    op.drop_table('partidos')
    op.drop_table('jugadores')
    # ### end Alembic commands ###
